spring:
  profiles:
    active: dev  #这是默认去找到文件
---
spring:
  profiles: dev
  application:
      name: microservice-zuul-gateway
server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    aigouEmployee.serviceId: employee-provider
    aigouEmployee.path: /employee/**  # 匹配 /xxx开头的请求映射到user-provider服务上
  #产品的服务路由:
    aigouProduct.serviceId: aigou-product
    aigouProduct.path: /product/**
    aigouCommon.serviceId: common-privoder
    aigouCommon.path: /common/**
  ignored-services: "*" #user-provider #忽略直接使用服务名访问  *忽略所有的
  prefix: /aixue   # 访问前缀

---
spring:
  profiles: test
  application:
      name: microservice-zuul-gateway
server:
  port: 9528
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    aigouEmployee.serviceId: employee-provider
    aigouEmployee.path: /employee/**  # 匹配 /xxx开头的请求映射到user-provider服务上
  #产品的服务路由:
    aigouProduct.serviceId: aigou-product
    aigouProduct.path: /product/**
    aigouCommon.serviceId: common-privoder
    aigouCommon.path: /common/**
  ignored-services: "*" #user-provider #忽略直接使用服务名访问  *忽略所有的
  prefix: /aixue   # 访问前缀